server:
  port: ${server.port}

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://192.168.1.5:3306/xianghong?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 000658ljx
    hikari:
      auto-commit: true
      connection-timeout: 20000
      max-lifetime: 1200000
      idle-timeout: 300000
      minimum-idle: 5
      maximum-pool-size: 12
  application:
    name: xianghong
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    active: ${spring_profiles_active}
  jackson:
    time-zone: GMT+8
browser:
  aegis:
    sdk:
      publicKey: no

redis:
  host: 192.168.1.5
  port: 6379
  password: 000658ljx
  timeout: 10000
  max-active: 100
  max-idle: 20
  min-idle: 5
  max-total: 4

