package com.xianghong.life.entity;

public class CashGiftEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_gift.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_gift.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_gift.money
     *
     * @mbg.generated
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_gift.style
     *
     * @mbg.generated
     */
    private Integer style;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_gift.relation_ship
     *
     * @mbg.generated
     */
    private String relationShip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_gift.id
     *
     * @return the value of cash_gift.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_gift.id
     *
     * @param id the value for cash_gift.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_gift.user_id
     *
     * @return the value of cash_gift.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_gift.user_id
     *
     * @param userId the value for cash_gift.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_gift.money
     *
     * @return the value of cash_gift.money
     *
     * @mbg.generated
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_gift.money
     *
     * @param money the value for cash_gift.money
     *
     * @mbg.generated
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_gift.style
     *
     * @return the value of cash_gift.style
     *
     * @mbg.generated
     */
    public Integer getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_gift.style
     *
     * @param style the value for cash_gift.style
     *
     * @mbg.generated
     */
    public void setStyle(Integer style) {
        this.style = style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_gift.relation_ship
     *
     * @return the value of cash_gift.relation_ship
     *
     * @mbg.generated
     */
    public String getRelationShip() {
        return relationShip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_gift.relation_ship
     *
     * @param relationShip the value for cash_gift.relation_ship
     *
     * @mbg.generated
     */
    public void setRelationShip(String relationShip) {
        this.relationShip = relationShip == null ? null : relationShip.trim();
    }
}