package com.xianghong.life.mapper;

import com.xianghong.life.entity.CashGiftEntity;
import com.xianghong.life.entity.CashGiftEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CashGiftEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_gift
     *
     * @mbg.generated
     */
    long countByExample(CashGiftEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_gift
     *
     * @mbg.generated
     */
    int deleteByExample(CashGiftEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_gift
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_gift
     *
     * @mbg.generated
     */
    int insert(CashGiftEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_gift
     *
     * @mbg.generated
     */
    int insertSelective(CashGiftEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_gift
     *
     * @mbg.generated
     */
    List<CashGiftEntity> selectByExample(CashGiftEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_gift
     *
     * @mbg.generated
     */
    CashGiftEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_gift
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CashGiftEntity record, @Param("example") CashGiftEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_gift
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CashGiftEntity record, @Param("example") CashGiftEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_gift
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CashGiftEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_gift
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CashGiftEntity record);
}