package com.xianghong.life.mapper;

import com.xianghong.life.entity.PublishContentEntity;
import com.xianghong.life.entity.PublishContentEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PublishContentEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    long countByExample(PublishContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    int deleteByExample(PublishContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    int insert(PublishContentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    int insertSelective(PublishContentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    List<PublishContentEntity> selectByExampleWithBLOBs(PublishContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    List<PublishContentEntity> selectByExample(PublishContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    PublishContentEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PublishContentEntity record, @Param("example") PublishContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PublishContentEntity record, @Param("example") PublishContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PublishContentEntity record, @Param("example") PublishContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PublishContentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PublishContentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PublishContentEntity record);
}